;;; cc-isearch-menu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cc-isearch-menu.el

(register-definition-prefixes "cc-isearch-menu" '("cc-isearch--toggle-"))

;;; End of scraped data

(provide 'cc-isearch-menu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cc-isearch-menu-autoloads.el ends here
