;;; casual-info-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual-info.el

 (autoload 'casual-info-tmenu "casual-info" nil t)
(register-definition-prefixes "casual-info" '("casual-info-new-info-frame"))


;;; Generated autoloads from casual-info-settings.el

(register-definition-prefixes "casual-info-settings" '("casual-info-"))


;;; Generated autoloads from casual-info-utils.el

(register-definition-prefixes "casual-info-utils" '("casual-info-"))


;;; Generated autoloads from casual-info-variables.el

(register-definition-prefixes "casual-info-variables" '("casual-info-use-unicode-symbols"))


;;; Generated autoloads from casual-info-version.el

(register-definition-prefixes "casual-info-version" '("casual-info-version"))

;;; End of scraped data

(provide 'casual-info-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-info-autoloads.el ends here
