;;; casual-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual.el

 (autoload 'casual-calc-tmenu "casual" nil t)
 (autoload 'casual-main-menu "casual" nil t)


;;; Generated autoloads from casual-calc--calc.el

(register-definition-prefixes "casual-calc--calc" '("casual-calc--"))


;;; Generated autoloads from casual-calc-algebra.el

(register-definition-prefixes "casual-calc-algebra" '("casual-calc-"))


;;; Generated autoloads from casual-calc-binary.el

(register-definition-prefixes "casual-calc-binary" '("casual-calc--calc-"))


;;; Generated autoloads from casual-calc-fileio.el

(register-definition-prefixes "casual-calc-fileio" '("casual-calc-"))


;;; Generated autoloads from casual-calc-financial.el

(register-definition-prefixes "casual-calc-financial" '("casual-calc--fin-"))


;;; Generated autoloads from casual-calc-graphics.el

(register-definition-prefixes "casual-calc-graphics" '("casual-calc--"))


;;; Generated autoloads from casual-calc-labels.el

(register-definition-prefixes "casual-calc-labels" '("casual-calc-"))


;;; Generated autoloads from casual-calc-predicates.el

(register-definition-prefixes "casual-calc-predicates" '("casual-calc-"))


;;; Generated autoloads from casual-calc-random.el

(register-definition-prefixes "casual-calc-random" '("casual-calc--random-interval-0-to-m"))


;;; Generated autoloads from casual-calc-settings.el

(register-definition-prefixes "casual-calc-settings" '("casual-calc-"))


;;; Generated autoloads from casual-calc-stack.el

(register-definition-prefixes "casual-calc-stack" '("casual-calc-"))


;;; Generated autoloads from casual-calc-vector.el

(register-definition-prefixes "casual-calc-vector" '("casual-calc--calc-histogram"))


;;; Generated autoloads from casual-calc-version.el

(register-definition-prefixes "casual-calc-version" '("casual-calc-version"))

;;; End of scraped data

(provide 'casual-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-autoloads.el ends here
